### PR TITLE
Serial expansion

### PR DESCRIPTION
**Pull request by zfields**
Created a new pull-request after the repo went public.

### CODE REVIEW

**Comment by zfields** [comment]
@turkycat @sidwarkd

**Comment by ooeygui** [comment]
Now that this is an independent repository, Is there a script to create nuget packages for this? 
How about integration tests which cover this specific component?

**Comment by turkycat** [comment]
I sign off on these changes, unit tests to come

**Comment by bethoma** [comment]
:+1: sign off

**Comment by zfields** [comment]
@sidwarkd Has validated the change set during his virtual-shields work. Kevin can you sign off before we pull?

**Comment by sidwarkd** [comment]
👍

**Pull request merged**
